%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-kobuki-driver
Version:        0.7.12
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS kobuki_driver package

License:        BSD
URL:            http://ros.org/wiki/kobuki_driver
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-noetic-ecl-command-line
Requires:       ros-noetic-ecl-console
Requires:       ros-noetic-ecl-converters
Requires:       ros-noetic-ecl-devices
Requires:       ros-noetic-ecl-geometry
Requires:       ros-noetic-ecl-mobile-robot
Requires:       ros-noetic-ecl-sigslots
Requires:       ros-noetic-ecl-time
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-ecl-build
BuildRequires:  ros-noetic-ecl-command-line
BuildRequires:  ros-noetic-ecl-console
BuildRequires:  ros-noetic-ecl-converters
BuildRequires:  ros-noetic-ecl-devices
BuildRequires:  ros-noetic-ecl-geometry
BuildRequires:  ros-noetic-ecl-mobile-robot
BuildRequires:  ros-noetic-ecl-sigslots
BuildRequires:  ros-noetic-ecl-time
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
C++ driver library for Kobuki: Pure C++ driver library for Kobuki. This is for
those who do not wish to use ROS on their systems.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Tue Sep 15 2020 Daniel Stonier <stonier@yujinrobot.com> - 0.7.12-1
- Autogenerated by Bloom

* Sun Sep 13 2020 Daniel Stonier <stonier@yujinrobot.com> - 0.7.10-1
- Autogenerated by Bloom

