Name:           ros-melodic-kobuki-dock-drive
Version:        0.7.8
Release:        0%{?dist}
Summary:        ROS kobuki_dock_drive package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/kobuki_dock_drive
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-ecl-geometry
Requires:       ros-melodic-ecl-linear-algebra
Requires:       ros-melodic-ecl-threads
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-ecl-build
BuildRequires:  ros-melodic-ecl-geometry
BuildRequires:  ros-melodic-ecl-linear-algebra
BuildRequires:  ros-melodic-ecl-threads

%description
Dock driving library for Kobuki. Users owning a docking station for Kobuki can
use this tool to develop autonomous docking drive algorithms.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Tue May 15 2018 Younghun Ju <yhju@yujinrobot.com> - 0.7.8-0
- Autogenerated by Bloom

