%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-kobuki-dock-drive
Version:        0.7.12
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS kobuki_dock_drive package

License:        BSD
URL:            http://ros.org/wiki/kobuki_dock_drive
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-noetic-ecl-geometry
Requires:       ros-noetic-ecl-linear-algebra
Requires:       ros-noetic-ecl-threads
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-ecl-build
BuildRequires:  ros-noetic-ecl-geometry
BuildRequires:  ros-noetic-ecl-linear-algebra
BuildRequires:  ros-noetic-ecl-threads
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Dock driving library for Kobuki. Users owning a docking station for Kobuki can
use this tool to develop autonomous docking drive algorithms.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Tue Sep 15 2020 Younghun Ju <yhju@yujinrobot.com> - 0.7.12-1
- Autogenerated by Bloom

* Sun Sep 13 2020 Younghun Ju <yhju@yujinrobot.com> - 0.7.10-1
- Autogenerated by Bloom

