Name:           ros-indigo-kobuki-driver
Version:        0.5.3
Release:        0%{?dist}
Summary:        ROS kobuki_driver package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/kobuki_driver
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-ecl-command-line
Requires:       ros-indigo-ecl-converters
Requires:       ros-indigo-ecl-devices
Requires:       ros-indigo-ecl-geometry
Requires:       ros-indigo-ecl-mobile-robot
Requires:       ros-indigo-ecl-sigslots
Requires:       ros-indigo-ecl-time
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-ecl-command-line
BuildRequires:  ros-indigo-ecl-converters
BuildRequires:  ros-indigo-ecl-devices
BuildRequires:  ros-indigo-ecl-geometry
BuildRequires:  ros-indigo-ecl-mobile-robot
BuildRequires:  ros-indigo-ecl-sigslots
BuildRequires:  ros-indigo-ecl-time

%description
C++ driver library for Kobuki: Pure C++ driver library for Kobuki. This is for
those who do not wish to use ROS on their systems.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Aug 04 2014 Daniel Stonier <stonier@yujinrobot.com> - 0.5.3-0
- Autogenerated by Bloom

