Name:           ros-indigo-kobuki-ftdi
Version:        0.6.0
Release:        0%{?dist}
Summary:        ROS kobuki_ftdi package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/kobuki_ftdi
Source0:        %{name}-%{version}.tar.gz

Requires:       libftdi-c++-devel
Requires:       libftdi-devel
Requires:       libusb-devel
Requires:       ros-indigo-ecl-command-line
BuildRequires:  libftdi-c++-devel
BuildRequires:  libftdi-devel
BuildRequires:  libusb-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-ecl-command-line

%description
Utilities for flashing and enabling Kobuki's USB connection. This package
contains tools for flashing the Kobuki's FTDI chip (usually done at the
factory). The special firmware for the FTDI chip (USB to serial converter)
enables it to appear as /dev/kobuki on the user's PC.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Aug 04 2014 Younghun Ju <yhju@yujinrobot.com> - 0.6.0-0
- Autogenerated by Bloom

* Mon Aug 04 2014 Younghun Ju <yhju@yujinrobot.com> - 0.5.3-0
- Autogenerated by Bloom

