Name:           ros-indigo-kobuki-dock-drive
Version:        0.6.2
Release:        0%{?dist}
Summary:        ROS kobuki_dock_drive package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/kobuki_dock_drive
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-ecl-geometry
Requires:       ros-indigo-ecl-linear-algebra
Requires:       ros-indigo-ecl-threads
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-ecl-build
BuildRequires:  ros-indigo-ecl-geometry
BuildRequires:  ros-indigo-ecl-linear-algebra
BuildRequires:  ros-indigo-ecl-threads

%description
Dock driving library for Kobuki. Users owning a docking station for Kobuki can
use this tool to develop autonomous docking drive algorithms.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sat Jan 09 2016 Younghun Ju <yhju@yujinrobot.com> - 0.6.2-0
- Autogenerated by Bloom

* Wed May 27 2015 Younghun Ju <yhju@yujinrobot.com> - 0.6.1-0
- Autogenerated by Bloom

* Mon Aug 04 2014 Younghun Ju <yhju@yujinrobot.com> - 0.6.0-0
- Autogenerated by Bloom

* Mon Aug 04 2014 Younghun Ju <yhju@yujinrobot.com> - 0.5.3-0
- Autogenerated by Bloom

